// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.28.3
// source: discovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The payload is JSON encoded discovery.Observation for PushObservation and
// JSON encoded sampled metrics for PushSample. Envelope fields are explicit so
// receivers can reject an old session before parsing untrusted payloads.
type DiscoveryReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	AgentId              string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId            string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionEpoch         uint64                 `protobuf:"varint,4,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	InstanceId           string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Stream               string                 `protobuf:"bytes,6,opt,name=stream,proto3" json:"stream,omitempty"`
	Sequence             uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SampledAt            string                 `protobuf:"bytes,8,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	CollectionDurationMs int64                  `protobuf:"varint,9,opt,name=collection_duration_ms,json=collectionDurationMs,proto3" json:"collection_duration_ms,omitempty"`
	Payload              []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DiscoveryReport) Reset() {
	*x = DiscoveryReport{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryReport) ProtoMessage() {}

func (x *DiscoveryReport) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryReport.ProtoReflect.Descriptor instead.
func (*DiscoveryReport) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryReport) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *DiscoveryReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DiscoveryReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DiscoveryReport) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *DiscoveryReport) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DiscoveryReport) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *DiscoveryReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DiscoveryReport) GetSampledAt() string {
	if x != nil {
		return x.SampledAt
	}
	return ""
}

func (x *DiscoveryReport) GetCollectionDurationMs() int64 {
	if x != nil {
		return x.CollectionDurationMs
	}
	return 0
}

func (x *DiscoveryReport) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DiscoveryAck struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId                 string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AcceptedSequence           uint64                 `protobuf:"varint,2,opt,name=accepted_sequence,json=acceptedSequence,proto3" json:"accepted_sequence,omitempty"`
	StoredRevision             int64                  `protobuf:"varint,3,opt,name=stored_revision,json=storedRevision,proto3" json:"stored_revision,omitempty"`
	Duplicate                  bool                   `protobuf:"varint,4,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	TopologyState              string                 `protobuf:"bytes,5,opt,name=topology_state,json=topologyState,proto3" json:"topology_state,omitempty"`
	ReasonCodes                []string               `protobuf:"bytes,6,rep,name=reason_codes,json=reasonCodes,proto3" json:"reason_codes,omitempty"`
	RouteReconcileRequired     bool                   `protobuf:"varint,7,opt,name=route_reconcile_required,json=routeReconcileRequired,proto3" json:"route_reconcile_required,omitempty"`
	AuthoritativeTopologyEpoch uint64                 `protobuf:"varint,8,opt,name=authoritative_topology_epoch,json=authoritativeTopologyEpoch,proto3" json:"authoritative_topology_epoch,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DiscoveryAck) Reset() {
	*x = DiscoveryAck{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryAck) ProtoMessage() {}

func (x *DiscoveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryAck.ProtoReflect.Descriptor instead.
func (*DiscoveryAck) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryAck) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DiscoveryAck) GetAcceptedSequence() uint64 {
	if x != nil {
		return x.AcceptedSequence
	}
	return 0
}

func (x *DiscoveryAck) GetStoredRevision() int64 {
	if x != nil {
		return x.StoredRevision
	}
	return 0
}

func (x *DiscoveryAck) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *DiscoveryAck) GetTopologyState() string {
	if x != nil {
		return x.TopologyState
	}
	return ""
}

func (x *DiscoveryAck) GetReasonCodes() []string {
	if x != nil {
		return x.ReasonCodes
	}
	return nil
}

func (x *DiscoveryAck) GetRouteReconcileRequired() bool {
	if x != nil {
		return x.RouteReconcileRequired
	}
	return false
}

func (x *DiscoveryAck) GetAuthoritativeTopologyEpoch() uint64 {
	if x != nil {
		return x.AuthoritativeTopologyEpoch
	}
	return 0
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\"\xdb\x02\n" +
	"\x0fDiscoveryReport\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_epoch\x18\x04 \x01(\x04R\fsessionEpoch\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\tR\x06stream\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"sampled_at\x18\b \x01(\tR\tsampledAt\x124\n" +
	"\x16collection_duration_ms\x18\t \x01(\x03R\x14collectionDurationMs\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\"\xe9\x02\n" +
	"\fDiscoveryAck\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12+\n" +
	"\x11accepted_sequence\x18\x02 \x01(\x04R\x10acceptedSequence\x12'\n" +
	"\x0fstored_revision\x18\x03 \x01(\x03R\x0estoredRevision\x12\x1c\n" +
	"\tduplicate\x18\x04 \x01(\bR\tduplicate\x12%\n" +
	"\x0etopology_state\x18\x05 \x01(\tR\rtopologyState\x12!\n" +
	"\freason_codes\x18\x06 \x03(\tR\vreasonCodes\x128\n" +
	"\x18route_reconcile_required\x18\a \x01(\bR\x16routeReconcileRequired\x12@\n" +
	"\x1cauthoritative_topology_epoch\x18\b \x01(\x04R\x1aauthoritativeTopologyEpoch2u\n" +
	"\x10DiscoveryService\x122\n" +
	"\x0fPushObservation\x12\x10.DiscoveryReport\x1a\r.DiscoveryAck\x12-\n" +
	"\n" +
	"PushSample\x12\x10.DiscoveryReport\x1a\r.DiscoveryAckB\tZ\a.;protob\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discovery_proto_goTypes = []any{
	(*DiscoveryReport)(nil), // 0: DiscoveryReport
	(*DiscoveryAck)(nil),    // 1: DiscoveryAck
}
var file_discovery_proto_depIdxs = []int32{
	0, // 0: DiscoveryService.PushObservation:input_type -> DiscoveryReport
	0, // 1: DiscoveryService.PushSample:input_type -> DiscoveryReport
	1, // 2: DiscoveryService.PushObservation:output_type -> DiscoveryAck
	1, // 3: DiscoveryService.PushSample:output_type -> DiscoveryAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
